# Generated by Django 3.2.16 on 2023-01-04 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20221221_2217'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
